### ISSUE TITLE
[Web UI] Apply search on shopping centers, status, and assets list

### ISSUE THREAD

**Issue by AshishKapoor** [kapoor-tech/inventory-management#2]
## Todo:

- [ ] Create a component for search
- [ ] Hook it up on shopping centers and search by name
- [ ] Under assets list, search by name, or by status

**Comment by AshishKapoor** [comment]
![New Website Blue Mockup Instagram - Laptop](https://user-images.githubusercontent.com/5203107/104845544-03948500-58fc-11eb-83b0-f495b2f086a7.png)
